### ISSUE TITLE
Lazyload is not working

### ISSUE THREAD

**Issue by eltonjothi** [jaanauati/react-dfp#182] opened 2020-01-09 06:37 UTC
http://react-dfp.ml/dfpslotsprovider/lazyload/
The Lazyload just doesnt seem to work.
i tried several times but no luck..

**Comment by scott-thrillist** [comment] 2020-01-10 16:52
@jaanauati has this worked before? I've always wrapped my below-the-fold ad slots in intersection observer listeners.

**Comment by jaanauati** [comment] 2020-01-10 21:43
i think you guys are right, this seems to be broken, I usually test here: http://react-dfp.ml/dfpslotsprovider/lazyload/  before publishing versions to npm, but i'm pretty sure this was working well some months ago.

**Comment by kamalarieff** [comment] 2020-02-21 10:28
I'm experiencing this issue as well.

**Comment by jaanauati** [comment] 2020-02-24 21:13
thank you for your feedback @kamalarieff !, I've been poking w this issue last Friday but I unfortunately I haven't been able to find what the problem is..... Hopefully  I'll be able to invest another couple of hours on this during the week; will let you know guys if I have any findings.

**Comment by jaanauati** [comment] 2020-02-28 21:27
been testing w different releases, it seems like this feature got broken in v0.15.0.

**Comment by jaanauati** [comment] 2020-02-28 22:33
@eltonjothi @scott-thrillist @kamalarieff I figured it out, react-dfp itself is ok, the example in the documentation website got broken when we merged this commit: https://github.com/jaanauati/react-dfp/commit/3a2932ec780248fe8146c1528ab7eed83784f171#diff-6264da2a3445a0b3ed0ddc2ca0272dc9L217.

I have already pushed the fix and it seems that the example is working well again (https://github.com/jaanauati/react-dfp-website/pull/45).

**Closed** 2020-03-02 22:28 UTC
Labels: bug
