### ISSUE TITLE
Receiving Exception in queued GPT command TypeError in console when loading ad. 

### ISSUE THREAD

**Issue by epiro-tm** [jaanauati/react-dfp#14] opened 2017-02-24 22:15 UTC
I receive the following error intermittently when displaying an ad unit:

```Exception in queued GPT command TypeError: Cannot read property 'addService' of null```

![screen_shot_2017-02-24_at_3 06 39_pm 1](https://cloud.githubusercontent.com/assets/12701311/23322897/2c13a998-fab4-11e6-984c-119421656a36.png)

The ad still shows with no issues but I'd like for my console to be clean. Here is the code for the component using the ad. 

```
import React from 'react'
import { AdSlot, DFPManager } from 'react-dfp'
import { AboveTheFoldOnlyServerRender } from 'above-the-fold-only-server-render'

const AdDfp = props => {
  return (
    <AboveTheFoldOnlyServerRender skip>
      <div>
        <AdSlot sizes={props.viewports} adUnit={props.adUnit} dfpNetworkId={props.dfpNetworkId} />
        {DFPManager.load()}
      </div>
    </AboveTheFoldOnlyServerRender>
  )
}

export default AdDfp
```

I'm having trouble figuring out if its related to implementation or if its a bug with react-dfp. Please offer any information you have about this.

**Comment by jaanauati** [comment] 2017-03-09 22:29
It seems the problem is the nested `` `{DFPManager.load ()}` `` calls. DFPManager. load() is not meant to be called in this way (as part of your react rendered markup)you should call it once. For this case I'd suggest you to follow one of the following approaches:

1) either wrap your code with <DFPSlotsProvider />
```
<DFPSlotsProvider .... >
       .....
      <AdDfp .../>
      <AdDfp .../>
     ...
           <AdDfp .../>
</DFPSlotsProvider .... >
```

2) or just call ``` DFPManager.load(); ``` from componentDidMount() somewhere in one of the parent components.

Of course, dont forget to deleted {DFPManager.load ()} from your template.

I guess that #1 is what you definitively need. Take a peak to the docs, you can some global data there (i.e dfpNetworkId) avoiding repetition of code.

That said, and although the reported use case isn't the recommended way to implement this library, i'm keeping this ticket opened to analyze and fix the code issue.

@epiro-tm makes sense to u?
Thanks.

**Comment by jaanauati** [comment] 2017-03-12 05:25
Fixed in v0.3.7 (https://github.com/jaanauati/react-dfp/tree/0.3.7), thanks for reporting 🍻.

**Closed by jaanauati** 2017-03-12 05:25 UTC

**Comment by epiro-tm** [comment] 2017-03-13 17:56
@jaanauati thank you! I ended up with placing DFPManager.load() after a promise in componentDidMount() and the errors no longer appeared.

**Comment by slackday** [comment] 2017-09-14 13:05
Hi! I'm running into the same problem using `react-dfp@0.4.2`. I have wrapped my whole App in `<DFPSlotsProvider>` which contains four `<AdSlot>`.

Ads render fine but when I navigate to different page I get the error. One time per `<AdSlot>`. I can put `autoLoad={false}` but same problem when I call `.load()` .

Could I please get a implementation reference how to correctly call load inside a component?

**Comment by slackday** [comment] 2017-09-20 20:15
Managed to solve the issue in my case. I explicitly set the `slotId` to a string (which I got from Google DFP). When I removed this and sat `autoLoad={false}` and trigger `DFPManager.refresh();` in `componentDidMount()` everything works 👍

**Comment by ERPG** [comment] 2018-08-09 11:01
It's happen to me the same issue and I don't know where this come from.

This is the code that I have in my Website:
`
<script type="text/html" data-ena-comp="AsynchronousLoader" async data-src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<script>
</script>

<ins class="adsbygoogle {{ adsense.styleClass }}"
     style="display:inline-block;"
     data-ad-client="{{ adsense.pubId }}"
     data-ad-slot="{{ adsense.slot }}"></ins>

<script type="text/html" data-ena-comp="AsynchronousLoader">
(adsbygoogle = window.adsbygoogle || []).push({});
</script>`

Also load the GPT script this way:

`<script>
    var googletag = googletag || {};
    googletag.cmd = googletag.cmd || [];
</script>
<script type='text/javascript' data-ena-comp="AsynchronousLoader">
    var googletag = googletag || {};
    googletag.cmd = googletag.cmd || [];
    (function() {
        var gads = document.createElement('script');
        gads.async = true;
        gads.type = 'text/javascript';
        var useSSL = 'https:' == document.location.protocol;
        gads.src = (useSSL ? 'https:' : 'http:') +
                '//www.googletagservices.com/tag/js/gpt.js';
        var node = document.getElementsByTagName('script')[0];
        node.parentNode.insertBefore(gads, node);
    })();
</script>`

Could someone help me with this ?

**Comment by ERPG** [comment] 2018-08-09 11:02
`s`
